version: "3.9"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-local
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=senha123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/container-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s CADASTRO/senha123@localhost/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 10

  apicadastropessoa:
    build:
      context: ./ApiCadastroPessoa
      dockerfile: Dockerfile
    image: apicadastropessoa
    ports:
      - "8081:8080"  # HOST:CONTAINER
    depends_on:
      oracle-db:
        condition: service_healthy

volumes:
  oracle-data:
